Numpy - Numerical Python

  =>  numpy is a python library that provides numerical operations & array manupultion.

Advantages of numpy:


*   Allows mathematical operations
*   Fast operations



In [ ]:
# Installing numpy library
!pip install numpy


In [ ]:
# Importing numpy library
import numpy as np


How numpy arrays are more efficient & works faster than lists??

Lets compare it using time taken to process the same code

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list =[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.0009225710000002607


Time taken by numpy array

In [ ]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.0006982210000003874


Numpy arrays

In [ ]:
# list
l=[1,2,3,4,5]
print(l)
type(l)

[1, 2, 3, 4, 5]


list

In [ ]:
# numpy arrays creation
n=np.array([1,2,3,4,5])
print(n)
type(n)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating 0 dimensional array(scalar):
n=np.array(5)
print(n)
type(n)

5


numpy.ndarray

In [ ]:
n.shape

()

In [ ]:
# creating 1 dimensional array(vector)
n=np.array([1,2,3,4,5])
print(n)
type(n)


[1 2 3 4 5]


numpy.ndarray

In [ ]:
n.shape

(5,)

In [ ]:
# creatng 2 dimensional array(matrix):
n=np.array([[1,2,3],[1,2,3]])
print(n)
type(n)

[[1 2 3]
 [1 2 3]]


numpy.ndarray

In [ ]:
n.shape

(2, 3)

Initial Placeholders in numpy arrays:


*   The methods used to create arrays initialized with specific defualt values.

*   Placeolders are useful to allocate memory for arrays before filling them with actual data.





   

1.   np.zeros

creates an array filled with zeros.




In [ ]:
n=np.zeros((3,4))
print(n)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



2.   np.ones

creates an array filled with ones



In [ ]:
n=np.ones((3,4))
print(n)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]





3.   np.empty

creates an array without initializing its elements



In [ ]:
n=np.empty((3,4)) # np.empty is more faster than np.zeros,np.ones to fill array later..
print(n)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]




4.   np.full

creates an array with a specified value






In [ ]:
n=np.full((3,4),10)
print(n)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]




5.   np.eye

creates 2D identity matrix(a square matrix with 1's on main diagonal and zeros elsewhere)



In [ ]:
# identity matrix
n=np.eye(3)
print(n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]




6.   np.arange

creates an array with evenly spaced values within specified range




In [ ]:
# 1D array with step size
n1=np.arange(0,10,2)
print(n1)


[0 2 4 6 8]


7.   np.linspace

creates an array with evenly spaced values within specified interval




In [ ]:
# An array with 5 points between 0 to 3 (specifying number of points b/w interval)
n2=np.linspace(0,3,5)
print(n2)

[0.   0.75 1.5  2.25 3.  ]


8.   np.random (random initial values)







In [ ]:
# An array with random values b/w 0 to 1
n=np.random.rand(3,4) #random uniform distribution
print(n)

[[0.08058177 0.44828739 0.4355331  0.81365506]
 [0.19790855 0.42873857 0.45349392 0.95118356]
 [0.62256785 0.1245624  0.77635085 0.33391964]]


In [ ]:
# An array with random values
n=np.random.randn(3,4) #random normal distribution
print(n)

[[ 1.40470134 -1.67829535  0.44049074  1.22384706]
 [-1.72025125  0.3353741  -0.70239129  0.78478022]
 [ 2.03304747  0.15228336  0.70904449  0.34465494]]


In [ ]:
# random integer values specified in range
n=np.random.randint(0,10,(3,4))
print(n)

[[1 7 4 3]
 [1 8 7 5]
 [1 1 1 8]]


In [ ]:
# converting lists into numpy arrays
list1=[1,2,3,4,5]
n=np.array(list1)
print(n)
type(n)

[1 2 3 4 5]


numpy.ndarray

Array properties(numpy)

In [ ]:
arr=np.array([[1,2,3],[1,2,3],[1,2,0]])
print(arr)

[[1 2 3]
 [1 2 3]
 [1 2 0]]


In [ ]:
print(arr.shape) # array dimensions

(3, 3)


In [ ]:
print(arr.dtype) # checking datatype of array

int64


In [ ]:
print(arr.size) # number of elements in array

9


In [ ]:
print(arr.ndim) # number of dimensions in array

2


2-D Array Indexing (Accessing elements)

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# accessing single element
print(arr[1,2]) # indexing starts from 0 for rows&columns
print(arr[2,2])

6
9


In [ ]:
# Accessing whole row
print(arr[2,:])                      # last row
#Accessing whole column
print(arr[:,2])                     #last column

[7 8 9]
[3 6 9]


In [ ]:
# Accessing subarray(slicing)
print(arr[0:2,0:2],"\n")
print(arr[1:3,1:3])

[[1 2]
 [4 5]] 

[[5 6]
 [8 9]]


In [ ]:
# Negative indexing
print(arr[-1,-1]) #last value

9


In [ ]:
# Mathematical operations on numpy
a=np.random.randint(1,10,(3,3))
b=np.random.randint(10,15,(3,3))
print(a,"\n")
print(b)

[[3 4 6]
 [3 2 9]
 [2 8 3]] 

[[10 11 13]
 [13 10 13]
 [13 14 13]]


In [ ]:
print(np.add(a,b))             #(a+b) also applicable
print(np.subtract(a,b))        #(a-b) also applicable
print(np.multiply(a,b))        #(a*b) also applicable
print(np.divide(a,b))          #(a/b) also applicable

[[13 15 19]
 [16 12 22]
 [15 22 16]]
[[ -7  -7  -7]
 [-10  -8  -4]
 [-11  -6 -10]]
[[ 30  44  78]
 [ 39  20 117]
 [ 26 112  39]]
[[0.3        0.36363636 0.46153846]
 [0.23076923 0.2        0.69230769]
 [0.15384615 0.57142857 0.23076923]]


In [ ]:
# power of elements
print(np.power(a,2))

[[ 9 16 36]
 [ 9  4 81]
 [ 4 64  9]]


Array manupilation

In [ ]:
print(a)
print(a.shape)

[[3 4 6]
 [3 2 9]
 [2 8 3]]
(3, 3)


In [ ]:
# Transpose of matrix
print(np.transpose(a)) # both same
print(a.T)
print(a.shape)

[[3 3 2]
 [4 2 8]
 [6 9 3]]
[[3 3 2]
 [4 2 8]
 [6 9 3]]
(3, 3)


In [ ]:
# reshaping matrix
n=np.random.randint(1,10,(2,3))
print(n)
print(n.shape)

[[9 6 4]
 [2 1 1]]
(2, 3)


In [ ]:
# reshaping
m=n.reshape(3,2)
print(m)
print(m.shape)

[[9 6]
 [4 2]
 [1 1]]
(3, 2)


In [ ]:
m2=n.reshape(2,3)
print(m2)
print(m2.shape)

[[9 6 4]
 [2 1 1]]
(2, 3)


In [ ]:
m3=n.reshape(6,1)
print(m3)
print(m3.shape)


[[9]
 [6]
 [4]
 [2]
 [1]
 [1]]
(6, 1)


In [ ]:
print(np.dot(a,b))

[[160 157 169]
 [173 179 182]
 [163 144 169]]


In [ ]:
n=np.array([1,2,3,4,5])
print(n)
print(np.max(n))
print(np.min(n))
print(np.mean(n))
print(np.median(n))
print(np.std(n))
print(np.var(n))

[1 2 3 4 5]
5
1
3.0
3.0
1.4142135623730951
2.0
