In [ ]:
import numpy as np

Creating a matrix using numpy

In [ ]:
mat=np.array([[2,3],[3,4]])
print(mat)

[[2 3]
 [3 4]]


In [ ]:
mat.shape

(2, 2)

In [ ]:
mat_2=np.array([[20,34,45],[33,45,65],[34,45,75]])
print(mat_2)

[[20 34 45]
 [33 45 65]
 [34 45 75]]


In [ ]:
mat_2.shape

(3, 3)

Matrices with random values

In [ ]:
rand_mat=np.random.rand(3,4)
print(rand_mat)

[[0.45296873 0.04140281 0.78162236 0.94399602]
 [0.04838539 0.25910494 0.34724608 0.53448247]
 [0.45028148 0.94916194 0.442858   0.47228278]]


In [ ]:
# creating matrix with random integers
rand_mat_int=np.random.randint(1,10,(3,4))
print(rand_mat_int)

[[7 7 2 1]
 [3 7 7 3]
 [6 3 6 4]]


Matrix with ones

In [ ]:
mat_ones=np.ones((2,4))
print(mat_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# matrix with zeros
mat_zeros=np.zeros((2,4),dtype=int)
print(mat_zeros)

[[0 0 0 0]
 [0 0 0 0]]


Identity matrix

In [ ]:
mat_iden=np.eye(3,3,dtype=int)
print(mat_iden)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Transpose of matrix

In [ ]:
x=np.random.randint(1,10,(3,4))
print(x)

[[4 4 8 2]
 [1 7 9 8]
 [5 5 9 5]]


In [ ]:
trans_x=np.transpose(x)
print(trans_x)

[[4 1 5]
 [4 7 5]
 [8 9 9]
 [2 8 5]]


In [ ]:
#Importng numpy library
import numpy as np

In [ ]:
a=np.array([[2,2],[3,4]])
b=np.array([[3,4],[4,5]])
print("Sum is \n",a+b)

Sum is 
 [[5 6]
 [7 9]]


In [ ]:
a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,10,(3,4))
print("Sum is/n",a+b)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

We get the error because a & b shapes are not same

In [ ]:
# with same shapes
a=np.random.randint(1,10,(3,4))
b=np.random.randint(1,10,(3,4))
print(a)
print("")
print(b)

[[1 6 1 7]
 [5 1 8 1]
 [2 1 6 7]]

[[4 7 1 7]
 [3 4 7 4]
 [8 6 5 1]]


In [ ]:
sum=np.add(a,b)
print(sum)

[[ 5 13  2 14]
 [ 8  5 15  5]
 [10  7 11  8]]


Matrix SUbtraction

In [ ]:
a=np.array([[5,3],[3,4]])
b=np.array([[3,4],[4,5]])
print("Difference is \n",a-b)

Difference is 
 [[ 2 -1]
 [-1 -1]]


In [ ]:
a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,10,(3,3))
print(a)
print("")
print(b)

[[7 1 7]
 [4 7 3]
 [2 6 5]]

[[3 7 4]
 [2 3 8]
 [3 3 6]]


In [ ]:
sub=np.subtract(a,b)
print(sub)

[[ 4 -6  3]
 [ 2  4 -5]
 [-1  3 -1]]


Matrix multiplication

In [ ]:
a=np.random.randint(1,10,(3,4))
b=np.random.randint(1,10,(4,3))
print(a)
print("")
print(b)

[[5 3 8 7]
 [8 1 2 2]
 [5 5 9 4]]

[[5 8 8]
 [9 3 1]
 [8 3 6]
 [4 4 2]]


In [ ]:
mul=np.dot(a,b)
print(mul)

[[144 101 105]
 [ 73  81  81]
 [158  98 107]]


Element wise matrix multiplication

In [ ]:
a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,10,(3,3))
print(a)
print("")
print(b)

[[3 6 1]
 [6 7 7]
 [1 9 2]]

[[8 7 4]
 [1 3 1]
 [2 7 8]]


In [ ]:
mult=np.multiply(a,b)
print(mult)

[[24 42  4]
 [ 6 21  7]
 [ 2 63 16]]


Multiplication=>np.dot function

Elementwise multiplication=>np.multiply(like sum)